require('plugins-config/airline')
require('plugins-config/coc')
require('plugins-config/gitsigns')
require('plugins-config/nvim-tree')
require('plugins-config/ruff')
require('plugins-config/treesitter')
require('plugins-config/telescope')
